### ISSUE TITLE
Using smaller base image for petclinic

### ISSUE THREAD

**Issue by dimahavrylevych** [blacksun0504/aws-cfn-petclinic#1]
It would be nice to reduce the size of the docker image using Alpine-based package

https://github.com/blacksun0504/aws-cfn-petclinic/blob/d85d2c2a59762b67308d68db0a7c9b94f77e8cf8/Job1/Dockerfile#L1

**Comment by blacksun0504** [comment]
Replaced with the Alpine-based image
